In [1]:
import numpy as np

In [2]:
frame_inds = np.array([0, 3, 7, 10, 14, 17, 20, 24, 27, 31])

In [3]:
print(frame_inds)

[ 0  3  7 10 14 17 20 24 27 31]


In [4]:
frame_inds = frame_inds[:, None] + np.arange(8)[None, :] * 8
print(frame_inds)

[[ 0  8 16 24 32 40 48 56]
 [ 3 11 19 27 35 43 51 59]
 [ 7 15 23 31 39 47 55 63]
 [10 18 26 34 42 50 58 66]
 [14 22 30 38 46 54 62 70]
 [17 25 33 41 49 57 65 73]
 [20 28 36 44 52 60 68 76]
 [24 32 40 48 56 64 72 80]
 [27 35 43 51 59 67 75 83]
 [31 39 47 55 63 71 79 87]]


In [5]:
frame_inds = np.concatenate(frame_inds)
print(frame_inds)

[ 0  8 16 24 32 40 48 56  3 11 19 27 35 43 51 59  7 15 23 31 39 47 55 63
 10 18 26 34 42 50 58 66 14 22 30 38 46 54 62 70 17 25 33 41 49 57 65 73
 20 28 36 44 52 60 68 76 24 32 40 48 56 64 72 80 27 35 43 51 59 67 75 83
 31 39 47 55 63 71 79 87]


In [6]:
frame_inds = frame_inds.reshape((-1, 8))
print(frame_inds)

[[ 0  8 16 24 32 40 48 56]
 [ 3 11 19 27 35 43 51 59]
 [ 7 15 23 31 39 47 55 63]
 [10 18 26 34 42 50 58 66]
 [14 22 30 38 46 54 62 70]
 [17 25 33 41 49 57 65 73]
 [20 28 36 44 52 60 68 76]
 [24 32 40 48 56 64 72 80]
 [27 35 43 51 59 67 75 83]
 [31 39 47 55 63 71 79 87]]


In [7]:
print(frame_inds.shape)

(10, 8)


In [8]:
from decord import VideoReader
from decord import cpu, gpu

vr = VideoReader("data/videos/Bowling/v_Bowling_g01_c07.avi", ctx=gpu(0))
print(len(vr))

131


In [9]:
safe_inds = frame_inds < len(vr)
unsafe_inds = 1 - safe_inds
last_ind = np.max(safe_inds * frame_inds, axis=1)
new_inds = (safe_inds * frame_inds + (unsafe_inds.T * last_ind).T)
frame_inds = new_inds

print(frame_inds)
print(frame_inds.shape)

[[ 0  8 16 24 32 40 48 56]
 [ 3 11 19 27 35 43 51 59]
 [ 7 15 23 31 39 47 55 63]
 [10 18 26 34 42 50 58 66]
 [14 22 30 38 46 54 62 70]
 [17 25 33 41 49 57 65 73]
 [20 28 36 44 52 60 68 76]
 [24 32 40 48 56 64 72 80]
 [27 35 43 51 59 67 75 83]
 [31 39 47 55 63 71 79 87]]
(10, 8)


In [10]:
clips = [(vr.get_batch(clip_indices)).asnumpy() for clip_indices in frame_inds]

In [11]:
cc=np.stack(clips)
print(cc.shape)

(10, 8, 240, 320, 3)


In [13]:
import torch

x = torch.from_numpy(cc)
print(x.shape)

torch.Size([10, 8, 240, 320, 3])


In [14]:
print(type(x))

<class 'torch.Tensor'>
